sudo: required

language: c

services:
  - docker

before_script:
  - docker build --tag devel -f Dockerfile.dev .

script:
  - docker create --name develcontainer devel
  - mkdir cmv
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cmv-1.1.0/x/CMCV/build/CMCV/CMCV CMCV
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cmv-1.1.0/x/CMV/build/CMV/CMV CMV
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cmv-1.1.0/x/HMMCV/build/HMMCV/HMMCV HMMCV
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cmv-1.1.0/x/HMMV/build/HMMV/HMMV HMMV
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cmv-1.1.0/x/CMCWStoCMCV/build/CMCWStoCMCV/CMCWStoCMCV CMCWStoCMCV
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cmv-1.1.0/x/CMCtoHMMC/build/CMCtoHMMC/CMCtoHMMC CMCtoHMMC
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cmv-1.1.0/x/CMCtoHMMC/build/CMCtoHMMC/CMCtoHMMC CMCtoHMMC
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cmv-1.1.0/x/HMMCtoCMC/build/HMMCtoCMC/HMMCtoCMC HMMCtoCMC
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cmv-1.1.0/x/StockholmV/build/StockholmV/StockholmV StockholmV
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cmv-1.1.0/x/CMVJson/build/CMVJson/CMVJson CMVJson
  - cp LICENSE cmv
  - tar -cvzf cmv.tar.gz cmv


deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "cmv.tar.gz" 
  on:
    tags: true
